# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
use_sim_time: true

moveit_simple_controller_manager:
  controller_names:
    - scara_controller
    - gripper_controller

  scara_controller:
    type: FollowJointTrajectory
    joints:
      - 03_arm_link1_part1_joint
      - 04_arm_link2_part1_joint
      - 05_arm_link3_T_joint
      - 06_arm_base_fingers_R_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true

  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - 07_arm_finger_right_joint
      - 08_arm_finger_left_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true
